// src/pages/about.tsx
import { FC } from 'react';
import FadeUpComponent from '../components/fade-up-component';
import useLoaded from '../hooks/use-loaded';

interface AboutProps {}

const About: FC<AboutProps> = () => {
	const isLoaded = useLoaded();
	return (
		<div className={`${isLoaded ? 'fade-start' : ''} flex justify-center items-center h-[87vh]`}>
			<FadeUpComponent order={1}>
				<div className="neu-in px-6 py-3 text-2xl rounded-full font-semibold text-color0">About</div>
			</FadeUpComponent>
		</div>
	);
};

export default About;

// src/routes/whoami/about/+page.svelte
<script lang="ts">
    import FadeUpComponent from '@/components/fade-up-component.svelte';
    import { onMount } from 'svelte';

    let isLoaded = false;
    onMount(() => {
        setTimeout(() => {
            isLoaded = true;
        }, 300);
    });
</script>

<div class={`${isLoaded ? 'fade-start' : ''} flex h-[87vh] items-center justify-center`}>
    <FadeUpComponent order={1}>
        <div class="neu-in rounded-full px-6 py-3 text-2xl font-semibold text-color0">About</div>
    </FadeUpComponent>
</div>
