// src/pages/projects/[id].tsx
import { FC, useEffect, useState } from 'react';
import { BiLeftArrowAlt } from 'react-icons/bi';
import { FaGithub } from 'react-icons/fa';
import { IoRocketSharp } from 'react-icons/io5';
import { NavLink, useNavigate, useParams } from 'react-router-dom';
import FadeUpComponent from '../../components/fade-up-component';
import ImageSlideShow from '../../components/image-slideshow';
import useLoaded from '../../hooks/use-loaded';
import { IProject } from '../../interfaces/project';
import { useRootContext } from '../../contexts/root';
import { ENV_CDN_PORTFOLIO_BASE_URL } from '../../utils/constants';

interface ProjectDetailProps {}

const ProjectDetail: FC<ProjectDetailProps> = () => {
	const id = useParams<'id'>().id;
	const idx = parseInt(id!);
	const navigate = useNavigate();

	const { projects } = useRootContext();
	const isLoaded = useLoaded();
	const [project, setProject] = useState<IProject>();
	const [images, setImages] = useState<string[]>([]);

	useEffect(() => {
		if (!projects) return;

		const temp = projects[idx];
		if (!temp) return navigate('/projects');

		setProject(temp);
	});

	useEffect(() => {
		if (!project) return;
		(async () => {
			const temp: string[] = [];
			for (let i = 1; i <= project.imageCount; i++) {
				const img = `${ENV_CDN_PORTFOLIO_BASE_URL}/project-imgs/${project.imageDir}/${i}.png`;
				temp.push(img);
			}
			setImages(temp);
		})();
	}, [project]);

	if (!project) return <div>Loading...</div>;

	return (
		<div className={`${isLoaded ? 'fade-start' : ''} pt-4 pb-32 flex flex-col gap-4`}>
			<FadeUpComponent order={1}>
				<div className="flex justify-end w-full sm:justify-start">
					<NavLink to="/projects" className="neu-out hover:text-color0 w-fit px-4 py-1 rounded-3xl flex items-center">
						<BiLeftArrowAlt className="text-2xl" />
						Back to Projects
					</NavLink>
				</div>
			</FadeUpComponent>
			<FadeUpComponent order={1}>
				<ImageSlideShow images={images} />
			</FadeUpComponent>
			<FadeUpComponent order={2}>
				<div className="w-full flex gap-2 sm:gap-4">
					{project.repositories.map((repo, idx) => {
						return (
							<a key={idx} href={repo.url} target="_blank" className="flex items-center gap-2 rounded-2xl py-1 px-3 neu-out hover:text-color0 text-xl">
								{repo.type === 'app' ? <IoRocketSharp className="text-color0" /> : <FaGithub className="text-color0" />}
								<span className="font-semibold text-sm underline">{repo.label || 'Source Code'}</span>
							</a>
						);
					})}
				</div>
			</FadeUpComponent>
			<FadeUpComponent order={2}>
				<div className="w-full neu-in rounded-xl px-4 py-3">
					<span className="text-2xl">{project?.title}</span>
					<div className="mt-2 flex gap-2 text-color0 font-semibold text-[12px] flex-wrap">
						{project?.tags.map((tag, idx) => {
							return (
								<div key={idx} className="neu-out w-fit h-fit px-2 py-1 rounded-md">
									{tag}
								</div>
							);
						})}
					</div>
				</div>
			</FadeUpComponent>
			<FadeUpComponent order={3}>
				<div className="w-full neu-in px-4 py-3 rounded-xl">
					<span className="whitespace-pre-wrap">{project?.description}</span>
				</div>
			</FadeUpComponent>
		</div>
	);
};

export default ProjectDetail;

// src/routes/whoami/projects/[id]/+page.svelte
<script lang="ts">
    import { page } from '$app/stores';
    import FadeUpComponent from '@/components/fade-up-component.svelte';
    import { projects } from '@/stores/projects';
    import type { Project } from '@/types/project';
    import Icon from '@iconify/svelte';
    import { onMount } from 'svelte';
    import { ENV_CDN_PORTFOLIO_BASE_URL } from '@/utils/constants';
    import ImageSlideShow from '@/components/image-slide-show.svelte';

    let project: Project | undefined = undefined;
    let images: string[] = [];
    const getData = () => {
        if ($projects.length === 0) return;
        const idx = parseInt($page.params.id);
        project = $projects[idx];
    };
    $: $projects, getData();
    $: if (project) {
        const temp: string[] = [];
        for (let i = 1; i <= project.imageCount; i++) {
            const img = `${ENV_CDN_PORTFOLIO_BASE_URL}/project-imgs/${project.imageDir}/${i}.png`;
            temp.push(img);
        }
        images = temp;
    }

    let isLoaded = false;
    onMount(async () => {
        setTimeout(() => {
            isLoaded = true;
        }, 300);
    });
</script>

<div class={`${isLoaded ? 'fade-start' : ''} flex flex-col gap-4 pb-32 pt-4`}>
    {#if $projects.length === 0}
        <FadeUpComponent order={1}>
            <div class="text-lg font-semibold text-color0">Loading...</div>
        </FadeUpComponent>
    {:else if !project}
        <FadeUpComponent order={1}>
            <div class="text-lg font-semibold uppercase text-color0">Project Not Found</div>
        </FadeUpComponent>
    {:else}
        <FadeUpComponent order={1}>
            <div class="flex w-full justify-end sm:justify-start">
                <a href="/whoami/projects" class="neu-out flex w-fit items-center rounded-3xl px-4 py-1 hover:text-color0">
                    <Icon icon="mingcute:arrow-left-fill" />
                    Back to Projects
                </a>
            </div>
        </FadeUpComponent>
        <FadeUpComponent order={1}>
            <ImageSlideShow {images} />
        </FadeUpComponent>
        <FadeUpComponent order={2}>
            <div class="flex w-full gap-2 sm:gap-4">
                {#each project.repositories as repo, idx (idx)}
                    <a
                        href={repo.url}
                        target="_blank"
                        class="neu-out flex items-center gap-2 rounded-lg px-3 py-1 hover:text-color0"
                    >
                        {#if repo.type === 'app'}
                            <Icon icon="noto:rocket" />
                        {:else}
                            <Icon icon="skill-icons:github-light" />
                        {/if}
                        <span class="text-xs font-semibold underline">{repo.label || 'Source Code'}</span>
                    </a>
                {/each}
            </div>
        </FadeUpComponent>
        <FadeUpComponent order={2}>
            <div class="neu-in w-full rounded-xl px-4 py-3">
                <span class="text-2xl">{project?.title}</span>
                <div class="mt-2 flex flex-wrap gap-2 text-[12px] font-semibold text-color0">
                    {#each project.tags as tag, idx (idx)}
                        <div class="neu-in h-fit w-fit rounded-md px-2 py-1">
                            {tag}
                        </div>
                    {/each}
                </div>
            </div>
        </FadeUpComponent>
        <FadeUpComponent order={3}>
            <div class="neu-in w-full rounded-xl px-4 py-3">
                <span class="whitespace-pre-wrap">{project?.description}</span>
            </div>
        </FadeUpComponent>
    {/if}
</div>
