// src/app/(main)/projects/page.tsx
"use client";
import { FC } from "react";
import FadeUpComponent from "@/components/fade-up-component";
import ProjectCard from "@/components/project-card";
import useLoaded from "@/hooks/use-loaded";
import { useRootContext } from "@/contexts/root";

interface ProjectsProps {}

const Projects: FC<ProjectsProps> = () => {
	const { projects } = useRootContext();
	const isLoaded = useLoaded();

	return (
		<div className={`${isLoaded ? "fade-start" : ""} pt-4 pb-32 flex flex-col gap-4`}>
			<FadeUpComponent order={1}>
				<div className="flex justify-start w-full sm:hidden">
					<div className="neu-out text-color0 w-fit px-4 py-1 rounded-3xl flex items-center font-semibold">Projects</div>
				</div>
			</FadeUpComponent>
			<div className={`grid grid-cols-1 sm:grid-cols-2 gap-5`}>
				{projects?.map((project, idx) => {
					return (
						<FadeUpComponent key={idx} order={idx < 2 ? 1 : idx < 4 ? 2 : 3} mobileOrder={idx < 1 ? 1 : idx < 2 ? 2 : 3}>
							<ProjectCard idx={idx} project={project} />
						</FadeUpComponent>
					);
				})}
			</div>
		</div>
	);
};

export default Projects;

// src/routes/whoami/projects/+page.svelte
<script lang="ts">
    import FadeUpComponent from '@/components/fade-up-component.svelte';
    import ProjectCard from '@/components/project-card.svelte';
    import { projects } from '@/stores/projects';
    import { onMount } from 'svelte';

    let isLoaded = false;
    onMount(async () => {
        setTimeout(() => {
            isLoaded = true;
        }, 300);
    });
</script>

<div class={`${isLoaded ? 'fade-start' : ''} flex flex-col gap-4 pb-32 pt-4`}>
    <FadeUpComponent order={1}>
        <div class="flex w-full justify-start sm:hidden">
            <div class="neu-out flex w-fit items-center rounded-3xl px-4 py-1 font-semibold text-color0">Projects</div>
        </div>
    </FadeUpComponent>
    <div class={`grid grid-cols-1 gap-5 sm:grid-cols-2`}>
        {#each $projects as project, idx (idx)}
            <FadeUpComponent order={idx < 2 ? 1 : idx < 4 ? 2 : 3} mobileOrder={idx < 1 ? 1 : idx < 2 ? 2 : 3}>
                <ProjectCard {idx} {project} />
            </FadeUpComponent>
        {/each}
    </div>
</div>
