// src/components/main-navbar.svelte
<script lang="ts">
    import { isDark } from '@/stores/theme';
    import Button from './button.svelte';
    import NavItem from './nav-item.svelte';
    import Icon from '@iconify/svelte';
</script>

<nav
    class="sticky top-0 z-40 flex min-h-[60px] justify-center bg-light opacity-90 shadow-md hover:opacity-100 dark:bg-dark"
>
    <div class="flex w-[1024px] items-center justify-between px-12">
        <a href="/" class="text-2xl font-semibold text-color0"> Yudi </a>
        <div class="flex items-center gap-5">
            <Button
                onClick={() => isDark.update((prev) => !prev)}
                class="neu-out neu-out-active rounded-full p-2 text-yellow-400"
            >
                {#if $isDark}
                    <Icon icon="emojione:crescent-moon" />
                {:else}
                    <Icon icon="emojione-v1:sun" />
                {/if}
            </Button>

            <NavItem href="/">Home</NavItem>
            <NavItem href="/projects">Projects</NavItem>
            <NavItem href="/about">About</NavItem>
            <NavItem href="/contacts">Contacts</NavItem>
        </div>
    </div>
</nav>

// src/components/main-navbar.tsx
'use client';

import { BsMoonStarsFill, BsSunFill } from 'react-icons/bs';
import Link from 'next/link';
import { useRootContext } from '../contexts/root';
import Button from './button';
import NavItem from './nav-item';

const MainNavbar = () => {
    const { toggleDarkMode, isDark } = useRootContext();

    return (
        <nav className="sticky top-0 opacity-90 hover:opacity-100 bg-light dark:bg-dark shadow-md min-h-[60px] flex justify-center z-40">
            <div className="flex items-center px-12 justify-between w-[1024px]">
                <Link href="/" className="text-2xl font-semibold text-color0">
                    Yudi
                </Link>
                <div className="flex gap-5 items-center">
                    <Button
                        onClick={() => toggleDarkMode()}
                        className="neu-out neu-out-active p-2 rounded-full text-yellow-400"
                    >
                        {isDark ? <BsSunFill /> : <BsMoonStarsFill />}
                    </Button>

                    <NavItem to="/">Home</NavItem>
                    <NavItem to="/projects">Projects</NavItem>
                    <NavItem to="/about">About</NavItem>
                    <NavItem to="/contacts">Contacts</NavItem>
                </div>
            </div>
        </nav>
    );
};

export default MainNavbar;
