// src/components/profile-overview.svelte
<script lang="ts">
    import FadeUpComponent from './fade-up-component.svelte';
    import NeuIcon from './neu-icon.svelte';
    import NavItem from './nav-item.svelte';
    import LinkIcon from './link-icon.svelte';
    import Icon from '@iconify/svelte';
</script>

<div class="flex w-full flex-col items-start justify-evenly gap-4 md:flex-row-reverse">
    <FadeUpComponent order={1}>
        <div class="ml-auto mr-auto flex w-full items-center justify-center sm:w-1/3 md:w-2/3">
            <div class="neu-out w-fit rounded-full p-4">
                <img class="aspect-square w-[250px] rounded-full" src="/profile.jpg" alt="profile" />
            </div>
        </div>
    </FadeUpComponent>
    <FadeUpComponent order={1} mobileOrder={2}>
        <div class="flex w-full flex-col gap-4">
            <div class="neu-in flex flex-col items-start justify-start gap-1 rounded-2xl px-5 py-2">
                <span class="text-2xl font-semibold">Hi, I'm Yudi</span>
                <div class="flex items-center gap-2">
                    <NeuIcon class="text-color0">
                        <Icon icon="streamline:desktop-code-solid" />
                    </NeuIcon>
                    <span class="text-lg font-semibold">Software Engineer</span>
                </div>
                <span class="text-sm">I'm currently working as Software Engineer</span>
            </div>
            <div class="neu-in flex flex-col gap-4 rounded-2xl px-5 py-2">
                <div class="flex gap-4">
                    <NavItem
                        href="/contacts"
                        class="neu-out flex w-fit items-center gap-2 font-semibold hover:text-color0"
                    >
                        <NeuIcon class="neu-in">
                            <Icon icon="ri:send-plane-fill" />
                        </NeuIcon>
                        Contact me
                    </NavItem>
                    <a
                        target="_blank"
                        href="https://www.linkedin.com/in/yudialfayat"
                        class="neu-out flex items-center gap-2 rounded-lg px-5 font-semibold hover:text-color0"
                    >
                        <NeuIcon class="neu-in">
                            <Icon icon="mingcute:paper-fill" />
                        </NeuIcon>
                        Resume
                    </a>
                </div>
                <div class="flex gap-4">
                    <LinkIcon url="https://github.com/ylfyt">
                        <Icon icon="skill-icons:github-light" />
                    </LinkIcon>
                    <LinkIcon url="https://www.linkedin.com/in/yudialfayat">
                        <Icon icon="logos:linkedin-icon" />
                    </LinkIcon>
                    <LinkIcon url="mailto:yalfayat@gmail.com">
                        <Icon icon="skill-icons:gmail-light" />
                    </LinkIcon>
                </div>
            </div>
            <div class="neu-in mt-4 w-fit rounded-2xl px-5 py-2">
                <div class="mb-3 text-xl font-semibold">Current favorite technologies</div>
                <div class="flex gap-3">
                    <NeuIcon class="text-[24px]">
                        <Icon icon="logos:dotnet" />
                    </NeuIcon>
                    <NeuIcon class="text-[24px]">
                        <Icon icon="devicon:typescript" />
                    </NeuIcon>
                    <NeuIcon class="text-[24px]">
                        <Icon icon="logos:graphql" />
                    </NeuIcon>
                    <NeuIcon class="text-[24px]">
                        <Icon icon="logos:react" />
                    </NeuIcon>
                    <NeuIcon class="text-[24px]">
                        <Icon icon="logos:svelte-icon" />
                    </NeuIcon>
                    <NeuIcon class="text-[24px]">
                        <Icon icon="logos:tailwindcss-icon" />
                    </NeuIcon>
                </div>
            </div>
        </div>
    </FadeUpComponent>
</div>

// src/components/profile-overview.tsx
import { FC } from 'react';
import { HiOutlineDesktopComputer, HiOutlineMail } from 'react-icons/hi';
import NavItem from '../components/nav-item';
import { FaGithub, FaLinkedin } from 'react-icons/fa';
import NeuIcon from '../components/neu-icon';
import { BiPaperPlane } from 'react-icons/bi';
import { SiDotnet, SiGraphql, SiReact, SiSvelte, SiTailwindcss, SiTypescript } from 'react-icons/si';
import { BsFillFileEarmarkPersonFill } from 'react-icons/bs';
import LinkIcon from './link-icon';
import FadeUpComponent from './fade-up-component';

interface ProfileOverviewProps {}

const ProfileOverview: FC<ProfileOverviewProps> = () => {
	return (
		<div className="w-full flex flex-col md:flex-row-reverse gap-4 items-start justify-evenly">
			<FadeUpComponent order={1}>
				<div className="w-full sm:w-1/3 md:w-2/3 flex items-center justify-center ml-auto mr-auto">
					<div className="neu-out w-fit rounded-full p-4">
						<img className="w-[250px] aspect-square rounded-full" src={`/profile.jpg`} alt="profile" />
					</div>
				</div>
			</FadeUpComponent>
			<FadeUpComponent order={1} mobileOrder={2}>
				<div className="flex flex-col gap-4 w-full">
					<div className="flex flex-col justify-start neu-in px-5 py-2 gap-1 items-start rounded-2xl">
						<span className="text-2xl font-semibold">Hi, I'm Yudi</span>
						<div className="flex items-center gap-2">
							<NeuIcon className="text-color0" icon={<HiOutlineDesktopComputer />} />
							<span className="text-lg font-semibold">Software Engineer</span>
						</div>
						<span className="text-sm">I'm currently working as Software Engineer</span>
					</div>
					<div className="flex gap-4 flex-col neu-in py-2 px-5 rounded-2xl">
						<div className="flex gap-4">
							<NavItem to="/contacts" className="neu-out flex items-center gap-2 w-fit hover:text-color0 font-semibold">
								<NeuIcon className="neu-in" icon={<BiPaperPlane />} />
								Contact me
							</NavItem>
							<a target="_blank" href="https://www.linkedin.com/in/yudialfayat" className="neu-out flex items-center gap-2 px-5 hover:text-color0 font-semibold rounded-lg">
								<NeuIcon className="neu-in" icon={<BsFillFileEarmarkPersonFill />} />
								Resume
							</a>
						</div>
						<div className="flex gap-4">
							<LinkIcon url="https://github.com/ylfyt" icon={<FaGithub size={24} />} />
							<LinkIcon url="https://www.linkedin.com/in/yudialfayat" icon={<FaLinkedin size={24} />} />
							<LinkIcon url="mailto:yalfayat@gmail.com" icon={<HiOutlineMail size={24} />} />
						</div>
					</div>
					<div className="mt-4 neu-in rounded-2xl w-fit px-5 py-2">
						<div className="text-xl mb-3 font-semibold">Current favorite technologies</div>
						<div className="flex gap-3">
							<NeuIcon className="text-[24px]" icon={<SiDotnet />} />
							<NeuIcon className="text-[24px]" icon={<SiTypescript />} />
							<NeuIcon className="text-[24px]" icon={<SiGraphql />} />
							<NeuIcon className="text-[24px]" icon={<SiReact />} />
							<NeuIcon className="text-[24px]" icon={<SiSvelte />} />
							<NeuIcon className="text-[24px]" icon={<SiTailwindcss />} />
						</div>
					</div>
				</div>
			</FadeUpComponent>
		</div>
	);
};

export default ProfileOverview;
