// src/components/project-card.svelte
<script lang="ts">
    import type { Project } from '@/types/project';
    import { ENV_CDN_PORTFOLIO_BASE_URL } from '@/utils/constants';
    import Icon from '@iconify/svelte';

    export let idx: number;
    export let project: Project;
</script>

<div class="neu-out hover:neu-out-long group flex w-full flex-col gap-4 rounded-lg px-4 py-3 transition-shadow">
    <a href={`/projects/${idx}`} class="flex flex-col gap-2">
        <div class="flex justify-center">
            <div class="flex aspect-video w-full items-center justify-center">
                <img
                    class="max-h-full"
                    src={`${ENV_CDN_PORTFOLIO_BASE_URL}/project-imgs/${project.imageDir}/1.png`}
                    alt="Project Thumbnail"
                />
            </div>
        </div>
        <div class="flex flex-col rounded-xl">
            <span class="font-semibold">{project.title}</span>
            <div class="mt-2 flex flex-wrap gap-2 text-[10px] font-semibold text-color0">
                {#each project.tags as tag, idx (idx)}
                    <div class="neu-in h-fit w-fit rounded-md px-2 py-1">
                        {tag}
                    </div>
                {/each}
            </div>
        </div>
    </a>
    <div class="flex gap-2 sm:gap-4">
        {#each project.repositories as repo, idx (idx)}
            <a
                href={repo.url}
                target="_blank"
                class="neu-out flex items-center gap-2 rounded-lg px-3 py-1 hover:text-color0"
            >
                {#if repo.type === 'app'}
                    <Icon icon="noto:rocket" />
                {:else}
                    <Icon icon="skill-icons:github-light" />
                {/if}
                <span class="text-xs font-semibold underline">{repo.label || 'Source Code'}</span>
            </a>
        {/each}
    </div>
</div>

// src/components/project-card.tsx
import { FC } from 'react';
import { FaGithub } from 'react-icons/fa';
import { IoRocketSharp } from 'react-icons/io5';
import { Link } from 'react-router-dom';
import { IProject } from '../interfaces/project';
import { ENV_CDN_PORTFOLIO_BASE_URL } from '../utils/constants';

interface ProjectCardProps {
	project: IProject;
	idx: number;
}

const ProjectCard: FC<ProjectCardProps> = ({ project, idx }) => {
	const thumbnailUrl = `${ENV_CDN_PORTFOLIO_BASE_URL}/project-imgs/${project.imageDir}/1.png`;

	return (
		<div className="group neu-out hover:neu-out-long transition-shadow py-3 px-4 rounded-lg flex flex-col gap-4 w-full">
			<Link to={`/projects/${idx}`} className="flex flex-col gap-2">
				<div className="flex justify-center">
					<div className="aspect-video flex items-center justify-center w-full">
						<img className="max-h-full" src={thumbnailUrl} alt="Project Thumbnail" />
					</div>
				</div>
				<div className="flex flex-col rounded-xl">
					<span className="font-semibold">{project.title}</span>
					<div className="mt-2 flex gap-2 text-color0 font-semibold text-[10px] flex-wrap">
						{project.tags.map((tag, idx) => {
							return (
								<div key={idx} className="neu-in w-fit h-fit px-2 py-1 rounded-md">
									{tag}
								</div>
							);
						})}
					</div>
				</div>
			</Link>
			<div className="flex gap-2 sm:gap-4">
				{project.repositories.map((repo, idx) => {
					return (
						<a key={idx} href={repo.url} target="_blank" className="flex items-center gap-2 rounded-lg py-1 px-3 neu-out hover:text-color0">
							{repo.type === 'app' ? <IoRocketSharp className="text-color0" /> : <FaGithub className="text-color0" />}
							<span className="text-xs font-semibold underline">{repo.label || 'Source Code'}</span>
						</a>
					);
				})}
			</div>
		</div>
	);
};

export default ProjectCard;
