// src/components/ProjectCard.svelte
<script lang="ts">
	import type { IProject } from '../interfaces/IProject';
	import { scale } from 'svelte/transition';

	export let project: IProject;
</script>

<div class="project-card glass" in:scale>
	<img src="./img/projects/{project.images[0]}" alt="" />
	{#if project.tags.length > 0}
		<div class="project-tags">
			{#each project.tags as tag}
				<div class="project-tag">{tag}</div>
			{/each}
		</div>
	{/if}
	<div class="description text-regular">
		{project.description}
	</div>
</div>

<style>
	.project-card {
		width: 250px;
		height: 400px;
		text-align: center;
	}

	.project-card:hover {
		cursor: pointer;
	}
	.project-card img {
		max-width: 100%;
		max-height: 50%;
	}
	.description {
		text-align: start;
		margin-top: 0;
	}

	.project-tags {
		margin-top: 10px;
		margin-bottom: 10px;
		display: flex;
		flex-wrap: wrap;
		font-size: 10px;
		gap: 10px;
	}

	.project-tag {
		padding: 2px 4px;
		border-radius: 5px;
		box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.2);
	}

	@media (max-width: 620px) {
		.project-card {
			width: 46%;
			min-height: 400px;
			height: fit-content;
		}
	}
</style>

// src/components/project-card.tsx
import { FC } from 'react';
import { NavLink } from 'react-router-dom';
import { IProject } from '../interfaces/IProject';

interface ProjectCardProps {
	project: IProject;
	idx: number;
}

const ProjectCard: FC<ProjectCardProps> = ({ project, idx }) => {
	return (
		<NavLink to={`/projects/${idx}`} className="neu-out hover:neu-out-long  transition-shadow py-3 px-4 rounded-lg flex flex-col gap-3 cursor-pointer">
			<div className="flex justify-center">
				<img className="h-[200px]" src={`${project.images.dir}/1.png`} alt="" />
			</div>
			<div className="flex flex-col py-2 rounded-xl">
				<span className="font-semibold">{project.title}</span>
				{/* <span className="text-sm">{project.description}</span> */}
				<div className="mt-2 flex gap-2 text-color0 font-semibold text-[10px] flex-wrap">
					{project.tags.map((tag, idx) => {
						return (
							<div key={idx} className="neu-in w-fit h-fit px-2 py-1 rounded-md">
								{tag}
							</div>
						);
					})}
				</div>
			</div>
		</NavLink>
	);
};
//
export default ProjectCard;
